apiVersion: apps/v1
kind: Deployment
metadata:
  name: desowa-service-deployment
  labels:
    app: desowa-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
        apps: desowa-service
  template:
    metadata:
      labels:
        apps: desowa-service
    spec:
      containers:
      - name: desowa-service
        image: mehmet2159/spring-hello
        ports:
        - containerPort: 8080