apiVersion: v1
kind: Service
metadata:
  name: desowa-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 8081
  type: NodePort    
  selector:
    apps: desowa-service